/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.crashlytics;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;

import android.app.Activity;

import com.google.firebase.crashlytics.FirebaseCrashlytics;

@Kroll.module(name="TitaniumCrashlytics", id="ti.crashlytics")
public class TitaniumCrashlyticsModule extends KrollModule
{

	// Standard Debugging variables

	private static final String LCAT = "TitaniumCrashlyticsModule";
	private static final boolean DBG = TiConfig.LOGD;

	public TitaniumCrashlyticsModule()
	{
		super();
	}

	// Methods
	@Kroll.setProperty
	public void setEnabled(boolean enabled)
	{
		FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(enabled);
	}

	@Kroll.method
	public void crash()
	{
		throw new RuntimeException("This is a crash");
	}

	@Kroll.method
	public void throwException()
	{
		try {
			throw new RuntimeException("This is a crash");
		} catch (RuntimeException e) {
			FirebaseCrashlytics.getInstance().recordException(e);
		}
	}

	@Kroll.method
	public void log(String message)
	{
		FirebaseCrashlytics.getInstance().log(message);
	}

	@Kroll.setProperty
	public void setUserId(String userIdentifier) {
		FirebaseCrashlytics.getInstance().setUserId(userIdentifier);
	}
}

